from datetime import datetime, timedelta

application_url = "https://wireless2.fcc.gov/UlsApp/ApplicationSearch/"
license_url = "https://wireless2.fcc.gov/UlsApp/UlsSearch/"

tabs = {
    "Main": "license.jsp?",
    "Admin": "licenseAdminSum.jsp?",
    "Locations": "licenseLocSum.jsp?",
    "Frequencies": "licenseFreqSum.jsp?",
    "Map": "licenseSiteMap.jsp?",
    "Market": "licenseMarketSum.jsp?",
    "Leases": "leasesList.jsp?",
}

r_services = {
    "AA": "Aviation Auxiliary Group",
    "AB": "Aural Microwave Booster",
    "AC": "Aircraft",
    "AD": "AWS-4 (2000-2020 MHz and 2180-2200 MHz)",
    "AF": "Aeronautical and Fixed",
    "AH": "AWS-H Block (at 1915-1920 MHz and 1995-2000 MHz)",
    "AI": "Aural Intercity Relay",
    "AR": "Aviation Radionavigation",
    "AS": "Aural Studio Transmitter Link",
    "AT": "AWS-3 (1695-1710 MHz, 1755-1780 MHz, and 2155-2180 MHz",
    "AW": "AWS (1710-1755 MHz and 2110-2155 MHz",
    "BA": "1390-1392 MHz Band, Market Area",
    "BB": "1392-1395 and 1432-1435 MHz Bands, Market Area",
    "BC": "1670-1675 MHz Band, Market Area",
    "BR": "Broadband Radio Service",
    "CA": "Commercial Air-ground Radiotelephone",
    "CB": "BETRS",
    "CD": "Paging and Radiotelephone",
    "CE": "Digital Electronic Message Service",
    "CF": "Common Carrier Fixed Point to Point Microwave",
    "CG": "General Aviation Air-ground Radiotelephone",
    "CJ": "Commercial Aviation Air-Ground Radiotelephone (800 MHz band)",
    "CL": "Cellular",
    "CM": "Commercial Operator",
    "CN": "PCS Narrowband",
    "CO": "Offshore Radiotelephone",
    "CP": "Part 22 VHF/UHF Paging [excluding 931 MHZ], Auctioned",
    "CR": "Rural Radiotelephone",
    "CT": "Local Television Transmission",
    "CW": "PCS Broadband",
    "CY": "1910-1915/1990-1995 MHz Bands, Market Area",
    "CZ": "Part 22 931 MHz Paging",
    "DV": "Multichannel Video Distribution AND Data Service",
    "ED": "Educational Broadband Service",
    "GB": "Business, 806-821/851-866 MHz, Conventional",
    "GC": "929-930 MHz Paging Systems, Auctioned",
    "GE": "Public Safety/Special Emergency and Public Safety, National Plan",
    "GF": "Public Safety Ntl Plan, 821-824/866-869 MHz, Conv.",
    "GI": "Other Indust/Land Transp, 896-901/935-940 MHz, Conv.",
    "GJ": "Business and Industrial/Land Transp, 809-824/854-869 MHz, Conv.",
    "GL": "900 MHz Conventional SMR (SMR, Site-Specific)",
    "GM": "800 MHz Conventional SMR (SMR, Site-Specific)",
    "GO": "Other Indust/Land Transp, 806-821/851-866 MHz, Conv.",
    "GP": "Public Safety/Spec Emerg, 806-821/851-866 MHz, Conv.",
    "GR": "SMR, 896-901/935-940 MHz, Conventional",
    "GS": "Private Carrier Paging, 929-930 MHz",
    "GU": "Business, 896-901/935-940 MHz, Conventional",
    "GX": "SMR, 806-821/851-866 MHz, Conventional",
    "HA": "Amateur",
    "HV": "Vanity",
    "IG": "Industrial/Business Pool, Conventional",
    "IK": "Industrial/Business Pool",
    "IQ": "Intelligent Transportation Service (Public Safety)",
    "LD": "Local Multipoint Distribution Service",
    "LN": "902-928 MHz Location Narrowband (Non-Multilateration)",
    "LP": "Broadcast Auxiliary Low Power",
    "LS": "Location and Monitoring Service, Multilateration (LMS)",
    "LV": "Low Power Wireless Assist Video Devices",
    "LW": "902-928 MHz Location Wideband (Grandfathered AVM)",
    "MA": "Marine Auxiliary Group",
    "MC": "Coastal Group",
    "MG": "Microwave Industrial/Business Pool",
    "MK": "Alaska Group",
    "MM": "Millimeter Wave 70/80/90 GHz",
    "MR": "Marine Radiolocation Land",
    "MS": "Multiple Address Service, Auctioned",
    "MW": "Microwave Public Safety Pool",
    "NC": "Nationwide Commercial 5 Channel, 220 MHz",
    "NN": "3650 - 3700 MHz",
    "PA": "Public Safety 4940-4990 MHz Band",
    "PC": "Public Coast Stations, Auctioned",
    "PE": "Digital Electronic Message Service",
    "PL": "3.5 GHz Band Priority Access License",
    "PM": "3.7 GHz Service",
    "PW": "Public Safety Pool, Conventional",
    "QA": "220-222 MHz Band, Auctioned",
    "QD": "Non-Nationwide Data, 220 MHz",
    "QM": "Non-Nationwide Public Safety/Mutual Aid, 220 MHz",
    "QO": "Non-Nationwide Other, 220 MHz",
    "QQ": "Intelligent Transportation Service (Non-Public Safety)",
    "QT": "Non-Nationwide 5 Channel Trunked, 220 MHz",
    "RP": "Broadcast Auxiliary Remote Pickup",
    "RR": "Restricted Operator",
    "RS": "Land Mobile Radiolocation",
    "SA": "Ship Recreational or Voluntarily Equipped",
    "SB": "Ship Compulsory Equipped",
    "SE": "Ship Exemption",
    "SG": "Conventional Public Safety 700MHz",
    "SL": "Public Safety 700 MHz Band",
    "SP": "700 MHz Public Safety Broadband Nationwide License",
    "SY": "Trunked Public Safety 700MHz",
    "TB": "TV Microwave Booster",
    "TC": "MSS Ancillary Terrestrial Component (ATC) Leasing",
    "TI": "TV Intercity Relay",
    "TN": "39 GHz, Auctioned",
    "TP": "TV Pickup",
    "TS": "TV Studio Transmitter Link",
    "TT": "TV Translator Relay",
    "TZ": "24 GHz Service",
    "UU": "Upper Microwave Flexible Use Service",
    "UM": "Unlicensed Wireless Microphone Registration",
    "WA": "Microwave Aviation",
    "WM": "Microwave Marine",
    "WP": "700 MHz Upper Band (Block D)",
    "WR": "Microwave Radiolocation",
    "WS": "Wireless Communications Service",
    "WT": "600 MHz Band",
    "WU": "700 MHz Upper Band (Block C)",
    "WX": "700 MHz Bands",
    "WY": "700 MHz Lower Band (Blocks A, B, E)",
    "WZ": "700 MHz Lower Band (Blocks C, D)",
    "YB": "Business, 806-821/851-866 MHz, Trunked",
    "YC": "SMR, 806-821/851-866 MHz, Auctioned",
    "YD": "SMR, 896-901/935-940 MHz, Auctioned",
    "YE": "Public Safety/Special Emergency and Public Safety, National Plan",
    "YF": "Public Safety Ntl Plan, 821-824/866-869 MHz, Trunked",
    "YG": "Industrial/Business Pool, Trunked",
    "YH": "SMR, 806-821/851-866 MHz, Auctioned (Rebanded YC license)",
    "YI": "Other Indust/Land Transp. 896-901/935-940 MHz, Trunked",
    "YJ": "Business and Industrial/Land Transp, 809-824/854-869, Trunked",
    "YK": "Industrial/Business Pool",
    "YL": "900 MHz Trunked SMR (SMR, Site-Specific)",
    "YM": "800 MHz Trunked SMR (SMR, Site-Specific)",
    "YO": "Other Indust/Land Transp. 806-821/851-866 MHz, Trunked",
    "YP": "Public Safety/Spec Emerg, 806-821/851-866 MHz, Trunked",
    "YS": "SMR, 896-901/935-940 MHz, Trunked",
    "YU": "Business, 896-901/935-940 MHz, Trunked",
    "YW": "Public Safety Pool, Trunked",
    "YX": "SMR, 806-821/851-866 MHz, Trunked",
    "ZA": "General Mobile Radio (GMRS)",
    "ZV": "218-219 MHz Service",
}

service_groups = {
    "All": r_services.keys(),
    "Amateur": ["HA", "HV"],
    "Ship": ["SA", "SB", "SE"],
    "Commercial/Restricted": ["CM", "RR"],
    "Aircraft": ["AC"],
    "GMRS": ["ZA"],
    "Cellular Radiotelephone": ["CL"],
    "Paging": ["CD", "CJ", "CP", "CZ", "GC", "GS"],
    "SMR": ["CY", "GR", "GX", "YC", "YD", "YS", "YX"],
    "Coast & Ground - Site-Based": ["AA", "AF", "AR", "MA", "MC", "MK", "MR"],
    "Part 90 - Land-mobile - Site Based": [
        "GB",
        "GE",
        "GF",
        "GI",
        "GJ",
        "GL",
        "GM",
        "GO",
        "GP",
        "GR",
        "GS",
        "GU",
        "GX",
        "IG",
        "IK",
        "IQ",
        "LN",
        "LP",
        "LV",
        "LW",
        "NC",
        "PA",
        "PW",
        "QD",
        "QM",
        "QO",
        "QQ",
        "QT",
        "RP",
        "RS",
        "SG",
        "SL",
        "SP",
        "SY",
        "YB",
        "YE",
        "YF",
        "YG",
        "YI",
        "YJ",
        "YK",
        "YL",
        "YM",
        "YO",
        "YP",
        "YS",
        "YU",
        "YW",
        "YX",
    ],
    "Microwave Site-Based": [
        "AB",
        "AI",
        "AS",
        "CE",
        "CF",
        "CT",
        "MG",
        "MM",
        "MW",
        "NN",
        "PE",
        "TB",
        "TI",
        "TP",
        "TS",
        "TT",
        "TZ",
        "WA",
        "WM",
        "WR",
    ],
    "Broadcast Auxiliary": [
        "AB",
        "AI",
        "AS",
        "LP",
        "LV",
        "RP",
        "TB",
        "TI",
        "TP",
        "TS",
        "TT",
    ],
    "Cellular-Like Service": ["CL", "CW", "CY", "GR", "GX", "YC", "YD", "YS", "YX"],
    "Market-based": [
        "AD",
        "AH",
        "AT",
        "AW",
        "BA",
        "BB",
        "BC",
        "BR",
        "CJ",
        "CL",
        "CN",
        "CP",
        "CW",
        "CY",
        "CZ",
        "DV",
        "ED",
        "GC",
        "LD",
        "LS",
        "MS",
        "PC",
        "PL",
        "PM",
        "QA",
        "TC",
        "TN",
        "TZ",
        "UU",
        "WP",
        "WS",
        "WT",
        "WU",
        "WX",
        "WY",
        "WZ",
        "YC",
        "YD",
        "YH",
        "ZV",
    ],
    "PCS Broadband": ["CW", "TC"],
    "BRS/EBS Services": ["BR", "ED"],
    "Leasable Services": [
        "AD",
        "AH",
        "AT",
        "AW",
        "BA",
        "BB",
        "BC",
        "BR",
        "CA",
        "CB",
        "CD",
        "CE",
        "CF",
        "CG",
        "CL",
        "CN",
        "CO",
        "CP",
        "CR",
        "CT",
        "CW",
        "CY",
        "CZ",
        "DV",
        "ED",
        "GB",
        "GC",
        "GE",
        "GF",
        "GI",
        "GJ",
        "GL",
        "GM",
        "GO",
        "GP",
        "GR",
        "GS",
        "GU",
        "GX",
        "IG",
        "IK",
        "IQ",
        "LD",
        "LS",
        "LW",
        "MG",
        "MS",
        "MW",
        "NC",
        "PC",
        "PE",
        "PL",
        "PM",
        "PW",
        "QA",
        "QD",
        "QM",
        "QO",
        "QQ",
        "QT",
        "SG",
        "SY",
        "TC",
        "TN",
        "TZ",
        "UU",
        "WA",
        "WM",
        "WP",
        "WR",
        "WS",
        "WT",
        "WU",
        "WY",
        "WZ",
        "YB",
        "YC",
        "YD",
        "YE",
        "YF",
        "YG",
        "YH",
        "YI",
        "YJ",
        "YK",
        "YL",
        "YM",
        "YO",
        "YP",
        "YS",
        "YU",
        "YW",
        "YX",
        "ZV",
    ],
    "Unlicensed Wireless Microphone Registration": ["UM"],
    "AWS": ["AD", "AH", "AT", "AW"],
    "MidBand": ["PM"],
}

serv_grps_form_encoding = {
    "All": "100",
    "Amateur": "1",
    "Ship": "2",
    "Commercial/Restricted": "3",
    "Aircraft": "4",
    "GMRS": "5",
    "Cellular Radiotelephone": "6",
    "Paging": "7",
    "SMR": "8",
    "Cost & Ground - Site-Based": "9",
    "Part 90 - Land-Mobile - Site Based": "10",
    "Microwave Site-Based": "11",
    "Broadcast Auxiliary": "12",
    "Cellular-Like Service": "13",
    "Market-based": "14",
    "PCS Broadband": "15",
    "BRS/EBS Services": "19",
    "Leasable Services": "20",
    "Unlicensed Wireless Microphone Registration": "21",
    "AWS": "22",
    "MidBand": "23",
}

states = [
    "Alabama",
    "Alaska",
    "American Samoa",
    "Arizona",
    "Arkansas",
    "Armed Forces - Pacific",
    "Armed Forces-Americas (excluding Canada)",
    "Armed Forces-Eur., Mid. East, Afr., Can.",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "District of Columbia",
    "Florida",
    "Georgia",
    "Guam",
    "Gulf of Mexico",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "North Mariana Islands",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Puerto Rico",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "United States Minor Islands",
    "Utah",
    "Vermont",
    "Virgin Islands",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
]

date_type = [
    "Select a date type",
    "Grant Date",
    "Effective Date",
    "Expiration Date",
    "Cancellation Date",
    "Last Action Date",
]

date_range = [
    "Select a fixed date range",
    "Today",
    "Yesterday",
    "In the last week",
    "In the last 2 weeks",
    "In the last 30 days",
    "In the last 60 days",
    "In the last 90 days",
    "In the last 180 days",
    "In the last year",
    "In the last 2 years",
    "Custom",
]

now = datetime.now()

date_values = {
    "Today": str(now.month) + "/" + str(now.day) + "/" + str(now.year),
    "Yesterday": str((now - timedelta(1)).month)
    + "/"
    + str((now - timedelta(1)).day)
    + "/"
    + str((now - timedelta(1)).year),
    "1 Week Ago": str((now - timedelta(7)).month)
    + "/"
    + str((now - timedelta(7)).day)
    + "/"
    + str((now - timedelta(7)).year),
    "2 Weeks Ago": str((now - timedelta(14)).month)
    + "/"
    + str((now - timedelta(14)).day)
    + "/"
    + str((now - timedelta(14)).year),
    "30 Days Ago": str((now - timedelta(30)).month)
    + "/"
    + str((now - timedelta(30)).day)
    + "/"
    + str((now - timedelta(30)).year),
    "60 Days Ago": str((now - timedelta(60)).month)
    + "/"
    + str((now - timedelta(60)).day)
    + "/"
    + str((now - timedelta(60)).year),
    "90 Days Ago": str((now - timedelta(90)).month)
    + "/"
    + str((now - timedelta(90)).day)
    + "/"
    + str((now - timedelta(90)).year),
    "180 Days Ago": str((now - timedelta(180)).month)
    + "/"
    + str((now - timedelta(180)).day)
    + "/"
    + str((now - timedelta(180)).year),
    "1 Year Ago": str((now - timedelta(365)).month)
    + "/"
    + str((now - timedelta(365)).day)
    + "/"
    + str((now - timedelta(365)).year),
    "2 Years Ago": str((now - timedelta(730)).month)
    + "/"
    + str((now - timedelta(730)).day)
    + "/"
    + str((now - timedelta(730)).year),
}

uls_datetype_vals = [
    "*",
    "uls_l_grant_date              ",
    "uls_l_issue_date              ",
    "uls_l_expired_date            ",
    "uls_l_cancellation_date       ",
    "uls_l_last_action_date        ",
]
date_type_dict = dict(zip(date_type, uls_datetype_vals))

state_abbrev = {
    "Alabama": "AL",
    "Alaska": "AK",
    "American Samoa": "AS",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "District of Columbia": "DC",
    "Florida": "FL",
    "Georgia": "GA",
    "Guam": "GU",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Northern Marianas": "MP",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Puerto Rico": "PR",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "U.S. Virgin Islands": "VI",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
}

abbrev_state = dict(map(reversed, state_abbrev.items()))

